### ISSUE TITLE
Yada w/ Postgress and insert json data: weird confusion of the parser when the json is for an array.

### ISSUE THREAD

**Issue by christopheleroy** [Novartis/YADA#88] opened 2018-10-18 21:42 UTC
No time to make it simpler and more private:

with query:
```
insert into shipment_request(reqid, user521, studyid, studyMembers, vendorFromEmails, vendorToEmails,
  shipAddress, requestStatus, requestSampleOverview)
 values(?n, ?v, ?v, json(?v), json(?v), json(?v),
  json(?v), ?v, json(?v))
```

and with a payload such as 
```
[
 {
  "qname": "BIOT insert new shipment request",
  "DATA": [
   {
    "reqid": 80111,
    "user521": "LEROYCH2",
    "studyID": "CABL001X2101",
    "studyMembers": "[{\"name\":\"Joe Arpagio\",\"email\":\"japargio@texas.us\"},{\"name\":\"Jack Daniels\",\"email\":\"jdaniels@texas.us\"}]",
    "vendorFromEmails": "[{\"name\":\"Chuck Cheeky\",\"email\":\"chuckc@cheeky.com\"}]",
    "vendorToEmails": "[{\"name\":\"Mary L. Lamb\",\"emails\":\"mllamb@gmail.com\"}]",
    "shipAddress": "[\"c/o Sammy\",\"PO Box 71211\",\"Austin TX 12311\",\"USA\"]",
    "requestStatus": "requested",
    "requestSampleOverview": "{\"tbd\":true}",
    "vendorFromId": "qui1",
    "vendorToId": "hgx1"
   }
  ]
 }
]
``` 
a weirdness is revealed:

The 'shipAddress' json field is an array of strings.

The yada query parser interprets this as a list of extra params:

```

2018-10-18 21:20:35,604 http-nio-8080-exec-8      DEBUG (Service.handleRequest: 137) Request query string is [j=%5B%7B%22qname%22%3A%22BIOT%20insert%20new%20shipment%20request%22%2C%22DATA%22%3A%5B%7B%22reqid%22%3A80111%2C%22user521%22%3A%22LEROYCH2%22%2C%22studyID%22%3A%22CABL001X2101%22%2C%22studyMembers%22%3A%22%5B%7B%5C%22name%5C%22%3A%5C%22Joe%20Arpagio%5C%22%2C%5C%22email%5C%22%3A%5C%22japargio%40texas.us%5C%22%7D%2C%7B%5C%22name%5C%22%3A%5C%22Jack%20Daniels%5C%22%2C%5C%22email%5C%22%3A%5C%22jdaniels%40texas.us%5C%22%7D%5D%22%2C%22vendorFromEmails%22%3A%22%5B%7B%5C%22name%5C%22%3A%5C%22Chuck%20Cheeky%5C%22%2C%5C%22email%5C%22%3A%5C%22chuckc%40cheeky.com%5C%22%7D%5D%22%2C%22vendorToEmails%22%3A%22%5B%7B%5C%22name%5C%22%3A%5C%22Mary%20L.%20Lamb%5C%22%2C%5C%22emails%5C%22%3A%5C%22mllamb%40gmail.com%5C%22%7D%5D%22%2C%22shipAddress%22%3A%5B%22c%2Fo%20Sammy%22%2C%22PO%20Box%2071211%22%2C%22Austin%20TX%2012311%22%2C%22USA%22%5D%2C%22requestStatus%22%3A%22requested%22%2C%22requestSampleOverview%22%3A%22%7B%5C%22tbd%5C%22%3Atrue%7D%22%2C%22vendorFromId%22%3A%22qui1%22%2C%22vendorToId%22%3A%22hgx1%22%7D%5D%7D%5D]
2018-10-18 21:20:35,604 http-nio-8080-exec-8      DEBUG (JSONParamsEntry.<init>: 151) JSONArray passed in is now [[Ljava.lang.String;@68a8eac8]
2018-10-18 21:20:35,604 http-nio-8080-exec-8      DEBUG (JSONParams.convertJSONObjects: 171)          Set [JsonParams] to [{BIOT insert new shipment request=com.novartis.opensource.yada.JSONParamsEntry@c4d4167}]
2018-10-18 21:20:35,605 http-nio-8080-exec-8      DEBUG (YADARequest.setParameterMap:3336)        Set [parameterMap] to [org.apache.catalina.util.ParameterMap@3c3811e6]
2018-10-18 21:20:35,605 http-nio-8080-exec-8      DEBUG (YADARequest.toString:1411) {j=[Ljava.lang.String;@5c3a51cb}
2018-10-18 21:20:35,605 http-nio-8080-exec-8      DEBUG (Service.handleRequest: 485) current settings:
{"j":["[{\"qname\":\"BIOT insert new shipment request\",\"DATA\":[{\"reqid\":80111,\"user521\":\"LEROYCH2\",\"studyID\":\"CABL001X2101\",\"studyMembers\":\"[{\\\"name\\\":\\\"Joe Arpagio\\\",\\\"email\\\":\\\"japargio@texas.us\\\"},{\\\"name\\\":\\\"Jack Daniels\\\",\\\"email\\\":\\\"jdaniels@texas.us\\\"}]\",\"vendorFromEmails\":\"[{\\\"name\\\":\\\"Chuck Cheeky\\\",\\\"email\\\":\\\"chuckc@cheeky.com\\\"}]\",\"vendorToEmails\":\"[{\\\"name\\\":\\\"Mary L. Lamb\\\",\\\"emails\\\":\\\"mllamb@gmail.com\\\"}]\",\"shipAddress\":[\"c/o Sammy\",\"PO Box 71211\",\"Austin TX 12311\",\"USA\"],\"requestStatus\":\"requested\",\"requestSampleOverview\":\"{\\\"tbd\\\":true}\",\"vendorFromId\":\"qui1\",\"vendorToId\":\"hgx1\"}]}]"]}
2018-10-18 21:20:35,605 http-nio-8080-exec-8      DEBUG (Finder.getQuery: 359) YADAQuery [BIOT insert new shipment request] retrieved from cache
2018-10-18 21:20:35,627 http-nio-8080-exec-8      DEBUG (QueryUtils.getAdaptorClass: 346) JDBCAdaptor class is [com.novartis.opensource.yada.adaptor.PostgreSQLAdaptor]
2018-10-18 21:20:35,628 http-nio-8080-exec-8      DEBUG (QueryUtils.getDataTypes: 972) data type of param [1] = n
2018-10-18 21:20:35,628 http-nio-8080-exec-8      DEBUG (QueryUtils.getDataTypes: 972) data type of param [2] = v
2018-10-18 21:20:35,628 http-nio-8080-exec-8      DEBUG (QueryUtils.getDataTypes: 972) data type of param [3] = v
2018-10-18 21:20:35,628 http-nio-8080-exec-8      DEBUG (QueryUtils.getDataTypes: 972) data type of param [4] = v
2018-10-18 21:20:35,628 http-nio-8080-exec-8      DEBUG (QueryUtils.getDataTypes: 972) data type of param [5] = v
2018-10-18 21:20:35,628 http-nio-8080-exec-8      DEBUG (QueryUtils.getDataTypes: 972) data type of param [6] = v
2018-10-18 21:20:35,628 http-nio-8080-exec-8      DEBUG (QueryUtils.getDataTypes: 972) data type of param [7] = v
2018-10-18 21:20:35,628 http-nio-8080-exec-8      DEBUG (QueryUtils.getDataTypes: 972) data type of param [8] = v
2018-10-18 21:20:35,628 http-nio-8080-exec-8      DEBUG (QueryUtils.getDataTypes: 972) data type of param [9] = v
2
```
and then:

```
------------------------------------------------------------
   INSERT/UPDATE/DELETE statement to execute:
------------------------------------------------------------
insert into shipment_request(reqid, user521, studyid, studyMembers, vendorFromEmails, vendorToEmails,
  shipAddress, requestStatus, requestSampleOverview)
 values(?, ?, ?, json(?), json(?), json(?),
  json(?), ?, json(?))

2018-10-18 21:20:35,642 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [1: reqid] has value [80111]
2018-10-18 21:20:35,642 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [2: user521] has value [LEROYCH2]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [3: studyid] has value [CABL001X2101]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [4: studyMembers] has value [[{"name":"Joe Arpagio","email":"japargio@texas.us"},{"name":"Jack Daniels","email":"jdaniels@texas.us"}]]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [5: vendorFromEmails] has value [[{"name":"Chuck Cheeky","email":"chuckc@cheeky.com"}]]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [6: vendorToEmails] has value [[{"name":"Mary L. Lamb","emails":"mllamb@gmail.com"}]]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [7: shipAddress] has value [c/o Sammy]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [7: shipAddress] has value [PO Box 71211]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [7: shipAddress] has value [Austin TX 12311]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [7: shipAddress] has value [USA]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [8: requestStatus] has value [requested]
2018-10-18 21:20:35,643 http-nio-8080-exec-8      DEBUG (QueryUtils.setPositionalParameterValues:1016) Column [9: requestSampleOverview] has value [{"tbd":true}]
2018-10-18 21:20:35,644 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.execute: 376) Executing query [BIOT insert new shipment request]
2018-10-18 21:20:35,644 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.setQueryParameter: 898) Setting param [ 1] of type [n] to: 80111
2018-10-18 21:20:35,644 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.setQueryParameter: 898) Setting param [ 2] of type [v] to: LEROYCH2
2018-10-18 21:20:35,644 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.setQueryParameter: 898) Setting param [ 3] of type [v] to: CABL001X2101
2018-10-18 21:20:35,644 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.setQueryParameter: 898) Setting param [ 4] of type [v] to: [{"name":"Joe Arpagio","email":"japargio@texas.us"},{"name":"Jack Daniels","email":"jdaniels@texas.us"}]
2018-10-18 21:20:35,644 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.setQueryParameter: 898) Setting param [ 5] of type [v] to: [{"name":"Chuck Cheeky","email":"chuckc@cheeky.com"}]
2018-10-18 21:20:35,644 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.setQueryParameter: 898) Setting param [ 6] of type [v] to: [{"name":"Mary L. Lamb","emails":"mllamb@gmail.com"}]
2018-10-18 21:20:35,644 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.setQueryParameter: 898) Setting param [ 7] of type [v] to: c/o Sammy
2018-10-18 21:20:35,644 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.setQueryParameter: 898) Setting param [ 8] of type [v] to: PO Box 71211
2018-10-18 21:20:35,645 http-nio-8080-exec-8      DEBUG (JDBCAdaptor.setQueryParameter: 898) Setting param [ 9] of type [v] to: Austin TX 12311
2018-10-18 21:20:35,656 http-nio-8080-exec-8      DEBUG (QueryManager.releaseResources: 532) Closing PreparedStatement
2018-10-18 21:20:35,661 http-nio-8080-exec-8      DEBUG (ProxyConnection.close: 234) HikariPool-BIOT - Executed rollback on connection org.postgresql.jdbc4.Jdbc4Connection@456c64f due to dirty commit state on close().
2018-10-18 21:20:35,661 http-nio-8080-exec-8      DEBUG (QueryManager.releaseResources: 534) PreparedStatement removed from map.
2018-10-18 21:20:35,661 http-nio-8080-exec-8      DEBUG (QueryManager.releaseResources: 556) Closing Connection
2018-10-18 21:20:35,661 http-nio-8080-exec-8      DEBUG (QueryManager.releaseResources: 561) QueryManager connection map has been cleared.
2018-10-18 21:20:35,661 http-nio-8080-exec-8      ERROR (Service.execute: 667) Prepared statement for update failed to execute
```

So the stringified json array  ``\"shipAddress\":[\"c/o Sammy\",\"PO Box 71211\",\"Austin TX 12311\",\"USA\"]`` confuses the parsed, so that the parameter 7, 8, and 9 are passed the members of the array. Since param 7 and 9 are passed to json(?v) to postgress and a string isn't valid json, the whole thing blows.

The other json properties (vendorFromEmails, vendorToEmails) are also arrays, but they are arrays of objects, so Yada isn't confused. But the shipAddress property is an array of strings.

Now, since I can change this to a payload of 
```
[
 {
  "qname": "BIOT insert new shipment request",
  "DATA": [
   {
    "reqid": 80111,
    "user521": "LEROYCH2",
    "studyID": "CABL001X2101",
    "studyMembers": "[{\"name\":\"Joe Arpagio\",\"email\":\"japargio@texas.us\"},{\"name\":\"Jack Daniels\",\"email\":\"jdaniels@texas.us\"}]",
    "vendorFromEmails": "[{\"name\":\"Chuck Cheeky\",\"email\":\"chuckc@cheeky.com\"}]",
    "vendorToEmails": "[{\"name\":\"Mary L. Lamb\",\"emails\":\"mllamb@gmail.com\"}]",
    "shipAddress": "{\"address\":[\"c/o Sammy\",\"PO Box 71211\",\"Austin TX 12311\",\"USA\"]}",
    "requestStatus": "requested",
    "requestSampleOverview": "{\"tbd\":true}",
    "vendorFromId": "qui1",
    "vendorToId": "hgx1"
   }
  ]
 }
]
```

the query works with absolutely no problem.

**Comment by varontron** [comment] 2018-10-23 15:39
This is the expected behavior.  Passing an array of strings for a column in `JSONParams` (or in `params` in some cases) is reserved for dynamic expansion of SQL `IN` clauses.   See the [JSONParams(JSONObject) constructor](https://github.com/Novartis/YADA/blob/a46187b169dcab077d84d7e28fde59a8c63ec675/yada-api/src/main/java/com/novartis/opensource/yada/JSONParamsEntry.java#L111).

**Comment by varontron** [comment] 2018-10-23 15:43
It might also work if the content were just a delimited string instead of a json array or object e.g., 
`"c/o Sammy","PO Box 71211","Austin TX 12311","USA"`

**Comment by varontron** [comment] 2018-10-23 15:52
recall also that the data passed to the service is ultimately converted into positional parameters for JDBC.

**Comment by christopheleroy** [comment] 2018-10-26 12:31
Well, no.

either this is the expected behavior but it is doing it  wrong, or you misunderstood me and this isn't the expected behavior.

I'm passed the problem because I changed the json content, but perhaps I can come-up with a much smaller and salient example. No urgency.

**Comment by varontron** [comment] 2018-10-26 20:10
I believe you didn't expect the behavior.  

YADA will take an array as a parameter value, but ultimately whether it's REST or JDBC, the values are marshalled into positional parameters, and parsed accordingly.  Meaning the values are stored as discrete values in an ordered list.  When an array is encountered as a param value for a SQL query, YADA assumes you have an `IN` clause. If there is one, YADA counts the values passed in this array and adds indexed JDBC parameter tokens to the SQL query and then applied in order.  If there isn't one, then the values are still applied in order.

**Comment by christopheleroy** [comment] 2018-10-26 23:09
Now - I see it. The JSON array isn't properly stringified, so it gets to be real JSON within the jsonParams payload. 
Not only did I change my JSON array to a JSON object, but then I must have suddenly properly stringified it.
Such mistake should have crashed / 500-ed .. but since Yada supports this case it successfully failed :)

**Comment by varontron** [comment] 2020-09-08 04:12
Won't fix.  works as intended.

**Closed by varontron** 2020-09-08 04:12 UTC
