### ISSUE TITLE
Query Parser crashes on some "NOT IN" clauses, tuple not in, not related to yada param

### ISSUE THREAD

**Issue by christopheleroy** [Novartis/YADA#16] opened 2016-04-15 20:28 UTC
The below query does not succeed to be parsed.
The reason might be perhaps the "NOT IN" clause is confusing the parser; but please note that it does not user any yada parameters ?x ..
Please note that the 'NOT IN' is also using a "tuple NOT IN" clause; which is probably nowhere in your test cases, but handy handy.

 INSERT into DISMISSED_DATA(inv_upload_id,excel_rix,md5,depot,orig_json,is_active,mod_emp521,mod_time)
 SELECT inv_upload_id,excel_rix,md5,depot,orig_json,1,mod_emp521,mod_time
 FROM PROCESSED_DATA
 WHERE INV_UPLOAD_ID=?n
  AND IS_IGNORE_ROW=1
  AND (depot,md5) not in (SELECT depot,md5 FROM DISMISSED_DATA where is_active=1)

The query works written as:

  INSERT into DISMISSED_DATA(inv_upload_id,excel_rix,md5,depot,orig_json,is_active,mod_emp521,mod_time)
 SELECT p.inv_upload_id,p.excel_rix,p.md5,p.depot,p.orig_json,1,p.mod_emp521,p.mod_time
 FROM PROCESSED_DATA p LEFT JOIN DISMISSED_DATA d on (p.depot=d.depot and d.md5=p.md5 and d.is_active=1)
 WHERE p.INV_UPLOAD_ID=?n
  AND p.IS_IGNORE_ROW=1
  AND d.depot is null

Example invocation:
http://localhost/yada.jsp?j=[{"qname":"DSMT+Commit+Dismissed+Rows+step+1b",DATA:[{"INV_UPLOAD_ID":"99"}]}]

**Comment by varontron** [comment] 2016-07-10 13:20
After upgrading to the latest version of JsqlParser, I couldn't reproduce this issue.  Further testing is required though before closing.  At the very least the original query should be tested.

**Comment by varontron** [comment] 2016-07-10 13:32
The original issue is not reproducible.  My suspicion is that the upgrade to the latest version of JSQLParser/JSqlParser fixed it, but it might also have been the mods to `IN` clause processing.

**Closed by varontron** 2016-07-10 13:32 UTC
Labels: bug
